services:
  - type: web
    name: github-token-api
    env: python
    plan: free
    repo: https://github.com/BattusaiKuroKame/colordock-token-api
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: GITHUB_APP_ID
        value: "123456"
      - key: GITHUB_PRIVATE_KEY
        value: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC...
          -----END RSA PRIVATE KEY-----
      - key: INSTALLATION_ID
        value: "789012"
      - key: REPO_OWNER
        value: "BattusaiKuroKame"
      - key: MANAGEMENT_REPO
        value: "BattusaiKuroKame/colordockmanagement"
      - key: MANAGEMENT_CREDENTIALS_PATH
        value: "credentials.csv"
      - key: MANAGEMENT_GITHUB_TOKEN
        value: "ghp_xxxYourPATxxx"
      - key: DATABASE_REPO
        value: "ColorDockDatabase"
      - key: TOKEN_STORE_FILE
        value: "tokens.json"
      - key: TOKEN_EXPIRY
        value: "300" #5 min
